import { Run, Space, Agent, RunEvent } from '../domain/types.js';
import { RunStatus, RunEventType } from '../domain/enums.js';
import { renderSafeMarkdown } from '../markdown/renderSafeMarkdown.js';
import { listSpacePresets } from '../presets/spacePresets.js';
import { quoteTagRegex, type NarrativeResult } from './NarrativeGenerator.js';

export interface RunReportInput {
  run: Run;
  space: Space;
  agents: Agent[];
  events: RunEvent[];
  narrative?: NarrativeResult;
}

export interface RunReportHtml {
  coverHtml: string;
  bodyHtml: string;
}

function escapeHtml(s: string): string {
  if (!s) return '';
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

export function renderRunReport(input: RunReportInput): RunReportHtml {
  const { run, space, agents, events } = input;
  const preset = space.presetId ? listSpacePresets().find((p) => p.id === space.presetId) : undefined;
  
  const coverHtml = `<!doctype html>
<html>
<head>
  <style>
    body { font-family: system-ui, -apple-system, sans-serif; color: #1e3a5f; margin: 2in 1in; text-align: center; }
    h1 { font-family: Georgia, 'Times New Roman', serif; font-size: 36pt; margin-bottom: 8px; color: #1e3a5f; }
    .preset { color: #5b6b7f; font-size: 14pt; margin-bottom: 40px; }
    .date { font-size: 12pt; color: #5b6b7f; margin-top: 60px; }
    .disclosure { font-size: 10pt; color: #cbd5e1; position: absolute; bottom: 1in; left: 0; right: 0; }
  </style>
</head>
<body>
  <h1>${escapeHtml(run.problem)}</h1>
  ${preset ? `<div class="preset">Methodology: ${escapeHtml(preset.name)}</div>` : ''}
  <div class="date">${escapeHtml(new Date(run.finishedAt ?? run.startedAt).toLocaleString())}</div>
  <div class="disclosure">Generated by a multi-agent AI collaboration.</div>
</body>
</html>`;

  let bodyHtml = `<!doctype html>
<html>
<head>
  <style>
    body { font-family: system-ui, -apple-system, sans-serif; color: #334155; font-size: 11pt; line-height: 1.5; margin: 0; }
    h2 { color: #1e293b; font-size: 18pt; border-bottom: 2px solid #cbd5e1; padding-bottom: 8px; margin-top: 0; margin-bottom: 16px; }
    .card { border: 1px solid #e2e8f0; border-radius: 8px; margin-bottom: 24px; padding: 16px; background: #fff; page-break-inside: avoid; }
    .card-header { font-weight: bold; font-size: 12pt; margin-bottom: 12px; color: #0f172a; display: flex; align-items: center; gap: 8px; }
    .manager-tag { font-size: 9pt; background: #e2e8f0; color: #475569; padding: 2px 8px; border-radius: 12px; font-weight: normal; }
    .tool-call { background: #f8fafc; border-left: 3px solid #94a3b8; padding: 8px 12px; margin: 12px 0; font-family: monospace; font-size: 10pt; white-space: pre-wrap; word-break: break-all; }
    .tool-name { font-weight: bold; color: #334155; margin-bottom: 4px; display: block; }
    .system-note { font-style: italic; color: #64748b; font-size: 10pt; margin: 16px 0; text-align: center; }
    .answer-box { background: #f8fafc; border: 1px solid #cbd5e1; padding: 20px; border-radius: 8px; margin-bottom: 40px; }
    .answer-box h3 { font-size: 14pt; margin-top: 0; margin-bottom: 12px; color: #1e3a5f; }
    .result-box { background: #fef2f2; border: 1px solid #fecaca; color: #991b1b; padding: 16px; border-radius: 8px; margin-bottom: 32px; }
    .stopped-box { background: #fffbeb; border: 1px solid #fde68a; color: #92400e; padding: 16px; border-radius: 8px; margin-bottom: 32px; }
    .agent-body { margin-top: 8px; }
  </style>
</head>
<body>`;

  if (run.status === RunStatus.Completed) {
    let answerHtml = '';
    if (input.narrative?.keyPoints && input.narrative.keyPoints.length > 0) {
      answerHtml += `<h3>Key Points</h3><ul>`;
      for (const point of input.narrative.keyPoints) {
        answerHtml += `<li>${escapeHtml(point)}</li>`;
      }
      answerHtml += `</ul><hr style="border:none; border-bottom: 1px solid #cbd5e1; margin: 16px 0;" />`;
    }
    answerHtml += `${renderSafeMarkdown(run.finalAnswer || '')}`;
    bodyHtml += `<h2>Final Answer</h2><div class="answer-box">${answerHtml}</div>`;
  } else if (run.status === RunStatus.Failed) {
    bodyHtml += `<div class="result-box"><strong>Run failed:</strong> ${escapeHtml(run.error || 'Unknown error')}</div>`;
  } else if (run.status === RunStatus.Stopped) {
    bodyHtml += `<div class="stopped-box"><strong>Stopped early</strong> &mdash; partial results below</div>`;
  }

  bodyHtml += `<h2>Full Conversation</h2>`;

  if (input.narrative) {
    // Same pattern the validator used - anything it skipped stays unconverted.
    // Quote text is flattened to one line so a multi-line quote doesn't fall
    // out of the single-line blockquote markdown; validation compares
    // whitespace-normalized text, so this stays faithful to the original.
    const markdown = input.narrative.narrativeMarkdown.replace(
      quoteTagRegex(),
      (_m, role: string, text: string) => `\n\n> "${text.replace(/\s+/g, ' ').trim()}"\n> — ${role}\n\n`
    );
    bodyHtml += `<div class="narrative-body" style="margin-bottom: 40px;">${renderSafeMarkdown(markdown)}</div>`;
  } else {
    let inCard = false;
  
  for (const ev of events) {
    if (ev.type === RunEventType.RoundStart) {
      if (inCard) bodyHtml += `</div>`;
      const agent = agents.find(a => a.id === ev.agentId);
      const role = agent ? agent.role : 'Unknown Agent';
      const isManager = agent?.isOrchestrator;
      const payload = ev.payload as { model?: string; phase?: string; cycle?: number; totalCycles?: number };
      let suffix = '';
      if (payload.totalCycles && payload.totalCycles > 1) {
        suffix = ` <span style="font-weight: normal; color: #64748b; font-size: 10pt;">&mdash; Cycle ${payload.cycle}/${payload.totalCycles} &middot; ${escapeHtml(payload.phase || '')}</span>`;
      }
      bodyHtml += `<div class="card"><div class="card-header">${escapeHtml(role)}${isManager ? '<span class="manager-tag">Manager</span>' : ''}${suffix}</div>`;
      inCard = true;
    } else if (ev.type === RunEventType.AgentMessage) {
      if (!inCard) { bodyHtml += `<div class="card">`; inCard = true; }
      const payload = ev.payload as { message?: { content?: string }, keyPoints?: string[] };
      bodyHtml += `<div class="agent-body">${renderSafeMarkdown(payload.message?.content || '')}</div>`;
      if (payload.keyPoints && payload.keyPoints.length > 0) {
        bodyHtml += `<div class="agent-keypoints" style="margin-top: 12px; padding-top: 12px; border-top: 1px dashed #cbd5e1;">`;
        bodyHtml += `<strong style="font-size: 10pt; color: #475569;">Key Points:</strong><ul style="margin: 4px 0 0 0; padding-left: 20px; color: #475569; font-size: 10pt;">`;
        for (const kp of payload.keyPoints) {
          bodyHtml += `<li>${renderSafeMarkdown(kp)}</li>`;
        }
        bodyHtml += `</ul></div>`;
      }
    } else if (ev.type === RunEventType.ToolCall) {
      if (!inCard) { bodyHtml += `<div class="card">`; inCard = true; }
      const payload = ev.payload as { toolCall?: { function?: { name: string; arguments: string } } };
      const toolCall = payload.toolCall?.function;
      if (toolCall) {
        bodyHtml += `<div class="tool-call"><span class="tool-name">${escapeHtml(toolCall.name)}</span>${escapeHtml(toolCall.arguments)}</div>`;
      }
    } else if (ev.type === RunEventType.System) {
      if (inCard) { bodyHtml += `</div>`; inCard = false; }
      const payload = ev.payload as { note?: string };
      const text = payload.note || '';
      if (text) {
        bodyHtml += `<div class="system-note">${escapeHtml(text)}</div>`;
      }
    }
    // ToolResult is explicitly ignored
    }
    if (inCard) bodyHtml += `</div>`;
  }

  bodyHtml += `</body></html>`;

  return { coverHtml, bodyHtml };
}
